language: haskell
ghc: 7.8


# Install GHC 7.8.2 on Travis using hvr's repo, see
# https://github.com/hvr/multi-ghc-travis
before_install:
      - sudo add-apt-repository -y ppa:hvr/ghc
      - sudo apt-get update
      - sudo apt-get install cabal-install-1.18 ghc-7.8.2
      - export PATH=/opt/ghc/7.8.2/bin:$PATH
      - ghc --version
      - cabal --version

install:
      # Travis automatically calls cabal update
      - make cabal-noupdate

script:
      - make fast

after_success:
      - cabal install hscolour
      - make haddock
      # run tests



notifications:
      email: false