language: haskell
ghc: 7.6

before_install: true "before_install"
install:        cabal install parsec lens-family optparse-applicative pipes pipes-network pipes-concurrency pipes-binary async time network-simple random monads-tf configurator
before_script:  true "before_script"
script:         make fast
after_success:  true "after_success"
after_failure:  true "after_failure"
after_script:   true "after_script"