language: haskell
ghc: 7.8



install:
      # Travis automatically calls cabal update
      - make cabal-noupdate
script:
      - make fast
after_success:
      - make haddock
      # run tests



notifications:
      email: false