language: haskell
ghc: 7.6



before_install:
      - true "before_install"


install:
      - cabal install --only-dependencies
                      --disable-optimization
                      --ghc-options=-w


before_script:
      - true "before_script"


script:
      - cabal configure --disable-optimization
      - cabal build


after_success:
      - true "after_success"


after_failure:
      - true "after_failure"


after_script:
      - true "after_script"