language: haskell
ghc: 7.6



before_install:
      - true "before_install"


install:
      - make cabal-init


before_script:
      - true "before_script"


script:
      - cabal build


after_success:
      - true "after_success"


after_failure:
      - true "after_failure"


after_script:
      - true "after_script"